(defun Append (L1 L2) 
	(cond ((null L1) L2)
		(T(cons (car L1)(Append (cdr L1)L2) )) ))
(print '-----------------------------------------------------------------------------------)
(print '"Prisoedineniye")
(print '-----------------------------------------------------------------------------------)
(print '"TEST 1")
(print (append '(a b c) 'd))
(print '"TEST 2")
(print (append '(1 2 3) '(A B C)))